namespace HZBot
{
    public class Bank_Inventory
    {
        #region Properties

        public int id { get; set; }
        public int character_id { get; set; }
        public int max_bank_index { get; set; }
        public int bank_item1_id { get; set; }
        public int bank_item2_id { get; set; }
        public int bank_item3_id { get; set; }
        public int bank_item4_id { get; set; }
        public int bank_item5_id { get; set; }
        public int bank_item6_id { get; set; }
        public int bank_item7_id { get; set; }
        public int bank_item8_id { get; set; }
        public int bank_item9_id { get; set; }
        public int bank_item10_id { get; set; }
        public int bank_item11_id { get; set; }
        public int bank_item12_id { get; set; }
        public int bank_item13_id { get; set; }
        public int bank_item14_id { get; set; }
        public int bank_item15_id { get; set; }
        public int bank_item16_id { get; set; }
        public int bank_item17_id { get; set; }
        public int bank_item18_id { get; set; }
        public int bank_item19_id { get; set; }
        public int bank_item20_id { get; set; }
        public int bank_item21_id { get; set; }
        public int bank_item22_id { get; set; }
        public int bank_item23_id { get; set; }
        public int bank_item24_id { get; set; }
        public int bank_item25_id { get; set; }
        public int bank_item26_id { get; set; }
        public int bank_item27_id { get; set; }
        public int bank_item28_id { get; set; }
        public int bank_item29_id { get; set; }
        public int bank_item30_id { get; set; }
        public int bank_item31_id { get; set; }
        public int bank_item32_id { get; set; }
        public int bank_item33_id { get; set; }
        public int bank_item34_id { get; set; }
        public int bank_item35_id { get; set; }
        public int bank_item36_id { get; set; }
        public int bank_item37_id { get; set; }
        public int bank_item38_id { get; set; }
        public int bank_item39_id { get; set; }
        public int bank_item40_id { get; set; }
        public int bank_item41_id { get; set; }
        public int bank_item42_id { get; set; }
        public int bank_item43_id { get; set; }
        public int bank_item44_id { get; set; }
        public int bank_item45_id { get; set; }
        public int bank_item46_id { get; set; }
        public int bank_item47_id { get; set; }
        public int bank_item48_id { get; set; }
        public int bank_item49_id { get; set; }
        public int bank_item50_id { get; set; }
        public int bank_item51_id { get; set; }
        public int bank_item52_id { get; set; }
        public int bank_item53_id { get; set; }
        public int bank_item54_id { get; set; }
        public int bank_item55_id { get; set; }
        public int bank_item56_id { get; set; }
        public int bank_item57_id { get; set; }
        public int bank_item58_id { get; set; }
        public int bank_item59_id { get; set; }
        public int bank_item60_id { get; set; }
        public int bank_item61_id { get; set; }
        public int bank_item62_id { get; set; }
        public int bank_item63_id { get; set; }
        public int bank_item64_id { get; set; }
        public int bank_item65_id { get; set; }
        public int bank_item66_id { get; set; }
        public int bank_item67_id { get; set; }
        public int bank_item68_id { get; set; }
        public int bank_item69_id { get; set; }
        public int bank_item70_id { get; set; }
        public int bank_item71_id { get; set; }
        public int bank_item72_id { get; set; }
        public int bank_item73_id { get; set; }
        public int bank_item74_id { get; set; }
        public int bank_item75_id { get; set; }
        public int bank_item76_id { get; set; }
        public int bank_item77_id { get; set; }
        public int bank_item78_id { get; set; }
        public int bank_item79_id { get; set; }
        public int bank_item80_id { get; set; }
        public int bank_item81_id { get; set; }
        public int bank_item82_id { get; set; }
        public int bank_item83_id { get; set; }
        public int bank_item84_id { get; set; }
        public int bank_item85_id { get; set; }
        public int bank_item86_id { get; set; }
        public int bank_item87_id { get; set; }
        public int bank_item88_id { get; set; }
        public int bank_item89_id { get; set; }
        public int bank_item90_id { get; set; }
        public int bank_item91_id { get; set; }
        public int bank_item92_id { get; set; }
        public int bank_item93_id { get; set; }
        public int bank_item94_id { get; set; }
        public int bank_item95_id { get; set; }
        public int bank_item96_id { get; set; }
        public int bank_item97_id { get; set; }
        public int bank_item98_id { get; set; }
        public int bank_item99_id { get; set; }
        public int bank_item100_id { get; set; }
        public int bank_item101_id { get; set; }
        public int bank_item102_id { get; set; }
        public int bank_item103_id { get; set; }
        public int bank_item104_id { get; set; }
        public int bank_item105_id { get; set; }
        public int bank_item106_id { get; set; }
        public int bank_item107_id { get; set; }
        public int bank_item108_id { get; set; }
        public int bank_item109_id { get; set; }
        public int bank_item110_id { get; set; }
        public int bank_item111_id { get; set; }
        public int bank_item112_id { get; set; }
        public int bank_item113_id { get; set; }
        public int bank_item114_id { get; set; }
        public int bank_item115_id { get; set; }
        public int bank_item116_id { get; set; }
        public int bank_item117_id { get; set; }
        public int bank_item118_id { get; set; }
        public int bank_item119_id { get; set; }
        public int bank_item120_id { get; set; }
        public int bank_item121_id { get; set; }
        public int bank_item122_id { get; set; }
        public int bank_item123_id { get; set; }
        public int bank_item124_id { get; set; }
        public int bank_item125_id { get; set; }
        public int bank_item126_id { get; set; }
        public int bank_item127_id { get; set; }
        public int bank_item128_id { get; set; }
        public int bank_item129_id { get; set; }
        public int bank_item130_id { get; set; }
        public int bank_item131_id { get; set; }
        public int bank_item132_id { get; set; }
        public int bank_item133_id { get; set; }
        public int bank_item134_id { get; set; }
        public int bank_item135_id { get; set; }
        public int bank_item136_id { get; set; }
        public int bank_item137_id { get; set; }
        public int bank_item138_id { get; set; }
        public int bank_item139_id { get; set; }
        public int bank_item140_id { get; set; }
        public int bank_item141_id { get; set; }
        public int bank_item142_id { get; set; }
        public int bank_item143_id { get; set; }
        public int bank_item144_id { get; set; }
        public int bank_item145_id { get; set; }
        public int bank_item146_id { get; set; }
        public int bank_item147_id { get; set; }
        public int bank_item148_id { get; set; }
        public int bank_item149_id { get; set; }
        public int bank_item150_id { get; set; }
        public int bank_item151_id { get; set; }
        public int bank_item152_id { get; set; }
        public int bank_item153_id { get; set; }
        public int bank_item154_id { get; set; }
        public int bank_item155_id { get; set; }
        public int bank_item156_id { get; set; }
        public int bank_item157_id { get; set; }
        public int bank_item158_id { get; set; }
        public int bank_item159_id { get; set; }
        public int bank_item160_id { get; set; }
        public int bank_item161_id { get; set; }
        public int bank_item162_id { get; set; }
        public int bank_item163_id { get; set; }
        public int bank_item164_id { get; set; }
        public int bank_item165_id { get; set; }
        public int bank_item166_id { get; set; }
        public int bank_item167_id { get; set; }
        public int bank_item168_id { get; set; }
        public int bank_item169_id { get; set; }
        public int bank_item170_id { get; set; }
        public int bank_item171_id { get; set; }
        public int bank_item172_id { get; set; }
        public int bank_item173_id { get; set; }
        public int bank_item174_id { get; set; }
        public int bank_item175_id { get; set; }
        public int bank_item176_id { get; set; }
        public int bank_item177_id { get; set; }
        public int bank_item178_id { get; set; }
        public int bank_item179_id { get; set; }
        public int bank_item180_id { get; set; }

        #endregion Properties
    }
}